// Walks the vendored `data/vendor/synth_manifest.json` + `data/vendor/methods/`
// at compile time and generates `$OUT_DIR/synth_examples_gen.rs`, a sorted
// static array mapping each command id to the verbatim text of its
// compiler-verified `.4dm` example file (embedded via `include_str!`).
//
// This keeps the final binary fully self-contained (no runtime file access)
// without pulling in the `include_dir` crate: everything here is std::fs plus
// serde_json (already a project dependency) to read the manifest.
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_path = "data/vendor/synth_manifest.json";
    println!("cargo:rerun-if-changed={manifest_path}");
    println!("cargo:rerun-if-changed=data/vendor/methods");

    let manifest_text = fs::read_to_string(manifest_path)
        .unwrap_or_else(|e| panic!("failed to read {manifest_path}: {e}"));
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text)
        .unwrap_or_else(|e| panic!("failed to parse {manifest_path}: {e}"));

    let files = manifest["files"]
        .as_object()
        .expect("synth_manifest.json missing top-level `files` object");

    let methods_dir = Path::new("data/vendor/methods");
    // BTreeMap sorts by command id so the generated array (and therefore the
    // build output) is deterministic across runs/machines.
    let mut entries: BTreeMap<String, String> = BTreeMap::new();

    for (rel_path, meta) in files {
        let command_id = meta["command_id"]
            .as_str()
            .unwrap_or_else(|| panic!("manifest entry {rel_path} missing command_id"));
        // rel_path looks like "Sources/Methods/Synth_<Name>.4dm"; the vendored
        // copy lives flattened under data/vendor/methods/ using the same file name.
        let file_name = Path::new(rel_path)
            .file_name()
            .unwrap_or_else(|| panic!("unexpected manifest rel_path shape: {rel_path}"))
            .to_str()
            .expect("non-utf8 manifest path");
        let full_path = methods_dir.join(file_name);
        if !full_path.exists() {
            panic!(
                "vendored synth example file missing: {} (referenced by manifest entry {rel_path} for command {command_id})",
                full_path.display()
            );
        }
        let abs = fs::canonicalize(&full_path).unwrap_or_else(|e| {
            panic!("failed to canonicalize {}: {e}", full_path.display())
        });
        let abs_str = abs
            .to_str()
            .unwrap_or_else(|| panic!("non-utf8 path: {}", abs.display()))
            .to_string();
        if let Some(prev) = entries.insert(command_id.to_string(), abs_str) {
            panic!("duplicate synth example for command {command_id} (previous path: {prev})");
        }
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    let dest = Path::new(&out_dir).join("synth_examples_gen.rs");

    let mut code = String::new();
    code.push_str(
        "/// Generated by build.rs: (command id, verbatim compiler-verified .4dm example text).\n",
    );
    code.push_str("pub static SYNTH_EXAMPLES: &[(&str, &str)] = &[\n");
    for (command_id, abs_path) in &entries {
        code.push_str(&format!(
            "    ({command_id:?}, include_str!({abs_path:?})),\n"
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
