//! Build-time embedded data. Everything here is baked into the binary at
//! compile time — no file or network access is performed at runtime.

/// The pinned `4d-static-docs` command IR (see `data/vendor/COMMIT` for
/// provenance: repo, commit sha, and fetch date).
pub static IR_JSON: &str = include_str!("../data/vendor/4d-command-ir.json");

/// Hand-curated deterministic colloquial/synonym expansion table used by the
/// tokenizer (see `index.rs`).
pub static ALIASES_JSON: &str = include_str!("../data/aliases.json");

// Generated by build.rs from data/vendor/synth_manifest.json +
// data/vendor/methods/*.4dm: `pub static SYNTH_EXAMPLES: &[(&str, &str)]`,
// mapping each command id to the verbatim text of its compiler-verified
// synthetic example file.
include!(concat!(env!("OUT_DIR"), "/synth_examples_gen.rs"));
